apiVersion: v1
kind: Pod
metadata:
  name: cpu-pod
  labels:
    kai.scheduler/queue: test  # Required queue assignment!
spec:
  schedulerName: kai-scheduler
  containers:
  - name: main
    image: ubuntu
    args: ["sleep", "infinity"]
    resources:
      requests:
        cpu: 100m
        memory: 250M
