apiVersion: v1
kind: Pod
metadata:
  name: default-pod
spec:
  # No schedulerName = uses default scheduler
  containers:
  - name: main
    image: ubuntu
    args: ["sleep", "infinity"]
    resources:
      requests:
        cpu: 100m
        memory: 250M
