apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-no-request
  labels:
    kai.scheduler/queue: test
  annotations:
    kai.scheduler/gpu-fraction: "0.5"  # Request half GPU
spec:
  schedulerName: kai-scheduler
  runtimeClassName: nvidia
  nodeSelector:
    nvidia.com/gpu.present: "true"
  containers:
  - name: main
    image: nvidia/cuda:12.2.0-base-ubuntu20.04
    command: ["sleep", "infinity"]
    env:
    - name: NVIDIA_VISIBLE_DEVICES
      value: "all"