apiVersion: v1
kind: Pod
metadata:
  name: gpu-demo-1
  labels:
    kai.scheduler/queue: test
    app: gpu-demo
  annotations:
    kai.scheduler/gpu-fraction: "0.1"  # 10% GPU
spec:
  schedulerName: kai-scheduler
  runtimeClassName: nvidia
  nodeSelector:
    nvidia.com/gpu.present: "true"
  containers:
  - name: gpu-workload
    image: nvidia/cuda:12.2.0-base-ubuntu20.04
    command: ["sleep", "infinity"]
    env:
    - name: NVIDIA_VISIBLE_DEVICES
      value: "all"