apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
  labels:
    kai.scheduler/queue: test
    app: sre-haiku
  annotations:
    kai.scheduler/gpu-fraction: "0.5"  # Request half GPU
spec:
  schedulerName: kai-scheduler
  runtimeClassName: nvidia
  nodeSelector:
    nvidia.com/gpu.present: "true"
  containers:
  - name: sre-haiku
    image: piotrzan/sre-haiku-generator:latest
    ports:
    - containerPort: 5000
    env:
    - name: NVIDIA_VISIBLE_DEVICES
      value: "all"
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: openai-secret
          key: api-key