apiVersion: v1
kind: Pod
metadata:
  name: kai-gpu-pod
  labels:
    kai.scheduler/queue: test
spec:
  schedulerName: kai-scheduler
  containers:
  - name: main
    image: nvidia/cuda:11.6.2-base-ubuntu20.04
    command: ["nvidia-smi", "-l", "60"]
    resources:
      limits:
        nvidia.com/gpu: "1"
      requests:
        nvidia.com/gpu: "1"
