kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  # GPU devices
  - hostPath: /dev/nvidia0
    containerPath: /dev/nvidia0
  - hostPath: /dev/nvidia-uvm
    containerPath: /dev/nvidia-uvm
  - hostPath: /dev/nvidia-uvm-tools
    containerPath: /dev/nvidia-uvm-tools
  - hostPath: /dev/nvidiactl
    containerPath: /dev/nvidiactl
  - hostPath: /dev/nvidia-modeset
    containerPath: /dev/nvidia-modeset
  
  # NVIDIA Binaries
  - hostPath: /usr/bin/nvidia-smi
    containerPath: /usr/bin/nvidia-smi
  
  # Essential NVIDIA libraries with correct version
  - hostPath: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.565.77
    containerPath: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.565.77
  - hostPath: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
    containerPath: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
  - hostPath: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so
    containerPath: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so
  - hostPath: /usr/lib/x86_64-linux-gnu/libcuda.so.565.77
    containerPath: /usr/lib/x86_64-linux-gnu/libcuda.so.565.77
  - hostPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
    containerPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
  - hostPath: /usr/lib/x86_64-linux-gnu/libcuda.so
    containerPath: /usr/lib/x86_64-linux-gnu/libcuda.so
  
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP
  
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "nvidia.com/gpu=true"