kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.31.0
  extraPortMappings:
  - containerPort: 30500
    hostPort: 5000
    protocol: TCP
- role: worker
  image: kindest/node:v1.31.0
  extraMounts:
  # nvkind replaces /dev/null with actual GPU device at runtime
  # This allows dynamic GPU assignment without hardcoding device paths
  - hostPath: /dev/null
    containerPath: /var/run/nvidia-container-devices/0