apiVersion: v1
kind: Pod
metadata:
  name: test-cpu-pod
  labels:
    kai.scheduler/queue: test
spec:
  schedulerName: kai-scheduler
  containers:
  - name: test
    image: busybox
    command: ["sleep", "3600"]
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"