apiVersion: v1
kind: Pod
metadata:
  name: vcluster-gpu-test
spec:
  nodeSelector:
    nvidia.com/gpu.present: "true"
  runtimeClassName: nvidia
  containers:
  - name: cuda
    image: nvidia/cuda:12.2.0-base-ubuntu20.04
    command: ["nvidia-smi", "-L"]