apiVersion: v1
kind: Pod
metadata:
  name: vcluster-kai-gpu
  labels:
    kai.scheduler/queue: default
spec:
  # schedulerName: kai-scheduler  # Would use KAI if installed in vCluster
  nodeSelector:
    nvidia.com/gpu.present: "true"
  runtimeClassName: nvidia
  containers:
  - name: cuda
    image: nvidia/cuda:12.2.0-base-ubuntu20.04
    command: ["nvidia-smi"]
    env:
    - name: NVIDIA_VISIBLE_DEVICES
      value: "all"